  pip install pillow
  pip install wconio2
  pip install colorama
  pip install multipledispatch
  pip install numpy
  pip install OpenCV-Python
  pip install pytweening
  pip install tk
  pip install pywinauto